feat: add docker stop/start logic during maintenance

diff --git a/dar-tools b/dar-tools
--- a/dar-tools
+++ b/dar-tools
@@ -1,5 +1,10 @@
 #!/usr/bin/env fish
-set -g fish_trace 1
+# set -g fish_trace 0
+set -g temp_files
+set -g docker_compose_directory ""
+set -g docker_compose_timeout 60
+set -g docker_backup_scripts_path ".docker/backup"
+
 function create
     set -l source "$argv[2]"
     set -l target "$argv[1]"
@@ -16,9 +21,15 @@ function create
     end
     
     set -l temp (mktemp --directory --tmpdir="$target")
+    set -g temp_files $temp_files $temp
     
     set -l last_dar (find_last_archive "$target")
-    
+
+    if before_docker_snapshot "$source"
+        log_info "Docker compose restart queued"
+        set -g docker_compose_directory "$source"
+    end
+
     if test -z "$last_dar"
         set -l name "full"
         log_info "Creating an archive: '$name'"
@@ -29,17 +40,23 @@ function create
     else
         set -l last_ref (string replace -r '\.[^.]+\.[^.]+$' '' $last_dar)
         set -l name "incremental-"(date +%Y%m%d-%H%M%S)
-        echo "Info: Creating an incremental archive '$name' based on '$last_ref'."
+        log_info "Creating an incremental archive '$name' based on '$last_ref'."
         if not dar --create "$temp/$name" --ref "$last_ref" --fs-root "$source" -Q --no-overwrite --compress=zstd $argv >/dev/null
             log_error "Failed to create an incremental archive"
             exit 1
         end
     end
-    
+
+    if test -n "$docker_compose_directory"
+        log_info "Executing queued docker compose restart"
+        if after_docker_snapshot "$source"
+            set -g docker_compose_directory ""
+        end
+    end
+
     set -l size (du --total --bytes "$temp" | tail -n 1 | cut -f 1)
     set -l count (find "$temp" -type f | wc -l)
     mv "$temp"/* "$target"
-    rm --dir $temp
     log_success "Archive created successfully"
     log_info "Size: $size bytes"
     log_info "Files: $count"
@@ -94,6 +111,11 @@ function extract
         log_error "Directory found but there no archives"
         exit 2
     end
+    
+    if before_docker_snapshot "$target"
+        log_info "Docker compose restart queued"
+        set -g docker_compose_directory "$target"
+    end
 
     set -l index 0
     get_archives "$archive_dir" | while read -l archive_basename
@@ -104,6 +126,14 @@ function extract
             exit 1
         end
     end
+    
+    if test -n "$docker_compose_directory"
+        log_info "Executing queued docker compose restart"
+        if after_docker_snapshot "$target"
+            set -g docker_compose_directory ""
+        end
+    end
+
     log_success "Completed"
 end
 
@@ -129,18 +159,47 @@ function compare
     end
     
     set -l source_temp (mktemp --directory --tmpdir="$temp_dir")
+    set -g temp_files $temp_files $source_temp
+    
     set -l archive_temp (mktemp --directory --tmpdir="$temp_dir")
-    log_info "Creating copy of the '$source'"
+    set -g temp_files $temp_files $archive_temp
+
+    if before_docker_snapshot "$source"
+        log_info "Docker container restart queued"
+        set -g docker_compose_directory "$source"
+    end
+
+    log_info "Creating temporary copy of the '$source'"
     cp -r "$source/." "$source_temp"
+
+    if test -n "$docker_compose_directory"
+        log_info "Executing queued docker compose restart"
+        if after_docker_snapshot "$source"
+            set -g docker_compose_directory ""
+        end
+    end
+
     log_info "Extracting the archive '$archive_dir'"
     extract "$archive_dir" "$archive_temp" -O
+    
     if not diff -rq "$source_temp" "$archive_temp"
         log_error "Source and archive are not equal"
         remove "$source_temp" "$archive_temp"
         exit 1
     end
-    remove "$source_temp" "$archive_temp"
     log_success "Source and archive are equal"
+end
+
+function before_docker_snapshot
+    set -l file "$argv[1]/$docker_backup_scripts_path/before"
+    test -x "$file"; and timeout $docker_compose_timeout "$file"; and return
+    return 1
+end
+
+function after_docker_snapshot
+    set -l file "$argv[1]/$docker_backup_scripts_path/after"
+    test -x "$file"; and timeout $docker_compose_timeout "$file"; and return
+    return 1
 end
 
 function get_archives
@@ -175,7 +234,23 @@ function log_error
     set_color red; echo -s "❌ Error: " $argv; set_color normal
 end
 
-# Main Execution Guard
+function on_exit --on-event fish_exit
+    if test -n "$docker_compose_directory"
+        log_error "Docker compose restart still queued before exit the program"
+        if after_docker_snapshot "$docker_compose_directory"
+            log_info "Docker compose restarted on exit"
+        else
+            log_error "Failed to start docker compose on exit"
+            exit 2
+        end
+    end
+    set -l count (count $temp_files)
+    if test $count -gt 0
+        log_info "Cleaning up $count files or directories"
+        rm -rf $temp_files
+    end
+end
+
 if test (count $argv) -lt 1
     echo "Usage: $_ {create|extract|verify} [args]"
     exit 1
@@ -183,6 +258,7 @@ end
 
 set -l action $argv[1]
 set -e argv[1] # Shift action out of arguments array
+
 
 switch "$action"
     case create
